import networkx as nx
import matplotlib.pyplot as plt


G = nx.Graph()
G.add_node("Entrance Room 1")
G.add_node("Entrance Room 2")
G.add_node("Entrance Room 3")
G.add_node("Entrance Room 4")
G.add_node("Entrance Room 5")
G.add_node("Entrance Room 6")
G.add_node("Entrance Room 7")
G.add_node("Entrance Room 8")
G.add_node("Entrance Room 9")
G.add_node("Entrance Room 10")
G.add_node("Entrance Room 11")
G.add_node("Entrance Room 12")
G.add_node("Entrance Room 13")
G.add_node("Entrance Room 14")
G.add_node("Entrance Room 15")
G.add_node("Entrance Room 16")
G.add_node("Entrance Room 17")
G.add_node("Entrance Room 18")
G.add_node("Entrance Save Room 1")
G.add_node("Entrance Save Room 2")
G.add_node("Entrance Warp Room 1")

G.add_node("Exit ER1/ER4")
G.add_node("Exit ER4/ER8")
G.add_node("Exit ER7/ER8")
G.add_node("Exit ER6/ER8")
G.add_node("Exit ER5/ER6")
G.add_node("Exit ER3/ER5")
G.add_node("Exit ER2/ER3")
G.add_node("Exit ER3/ESR1")
G.add_node("Exit ER8/ER10")
G.add_node("Exit ER8/ER9")
G.add_node("Exit ER10/ER11")
G.add_node("Exit ER11/ER12")
G.add_node("Exit ER11/ER13")
G.add_node("Exit ER13/ER14")
G.add_node("Exit ER14/ER15")
G.add_node("Exit ER15/ER16")
G.add_node("Exit ER15/ESR2")
G.add_node("Exit ER15/ER17")
G.add_node("Exit ER17/ER18")
G.add_node("Exit ER18/EWR1")

G.add_edge("Entrance Room 1", "Exit ER1/ER4")
G.add_edge("Entrance Room 4", "Exit ER1/ER4")
G.add_edge("Entrance Room 4", "Exit ER4/ER8")
G.add_edge("Entrance Room 8", "Exit ER4/ER8")
G.add_edge("Entrance Room 7", "Exit ER7/ER8")
G.add_edge("Entrance Room 8", "Exit ER7/ER8")
G.add_edge("Entrance Room 6", "Exit ER6/ER8")
G.add_edge("Entrance Room 8", "Exit ER6/ER8")
G.add_edge("Entrance Room 5", "Exit ER5/ER6")
G.add_edge("Entrance Room 6", "Exit ER5/ER6")
G.add_edge("Entrance Room 3", "Exit ER3/ER5")
G.add_edge("Entrance Room 5", "Exit ER3/ER5")
G.add_edge("Entrance Room 2", "Exit ER2/ER3")
G.add_edge("Entrance Room 3", "Exit ER2/ER3")
G.add_edge("Entrance Room 3", "Exit ER3/ESR1")
G.add_edge("Entrance Save Room 1", "Exit ER3/ESR1")
G.add_edge("Entrance Room 8", "Exit ER8/ER10")
G.add_edge("Entrance Room 10", "Exit ER8/ER10")
G.add_edge("Entrance Room 8", "Exit ER8/ER9")
G.add_edge("Entrance Room 9", "Exit ER8/ER9")
G.add_edge("Entrance Room 10", "Exit ER10/ER11")
G.add_edge("Entrance Room 11", "Exit ER10/ER11")
G.add_edge("Entrance Room 11", "Exit ER11/ER12")
G.add_edge("Entrance Room 12", "Exit ER11/ER12")
G.add_edge("Entrance Room 11","Exit ER11/ER13")
G.add_edge("Entrance Room 13","Exit ER11/ER13")
G.add_edge("Entrance Room 13","Exit ER13/ER14")
G.add_edge("Entrance Room 14","Exit ER13/ER14")
G.add_edge("Entrance Room 14", "Exit ER14/ER15")
G.add_edge("Entrance Room 15", "Exit ER14/ER15")
G.add_edge("Entrance Room 15", "Exit ER15/ER16")
G.add_edge("Entrance Room 16", "Exit ER15/ER16")
G.add_edge("Entrance Room 15","Exit ER15/ESR2")
G.add_edge("Entrance Save Room 2", "Exit ER15/ESR2")
G.add_edge("Entrance Room 15","Exit ER15/ER17")
G.add_edge("Entrance Room 17", "Exit ER15/ER17")
G.add_edge("Entrance Room 17", "Exit ER17/ER18")
G.add_edge("Entrance Room 18", "Exit ER17/ER18")
G.add_edge("Entrance Room 18", "Exit ER18/EWR1")
G.add_edge("Entrance Warp Room 1", "Exit ER18/EWR1")


nx.draw_spring(G, with_labels=False)

plt.show()